// Verbatim quotes only. Every entry is copied from the linked source, dated, and never paraphrased.
// `took` is our one-line reading of it: what the quote turned into in the loops folder.

export type Quote = {
  id: string;
  part: 'loops' | 'graphs';
  text: string;
  who: string;
  where: string;
  date: string;
  url: string;
  took: string;
  home?: boolean;
};

export const QUOTES: Quote[] = [
  {
    id: 'cherny-loops',
    part: 'loops',
    text: 'I don’t prompt Claude anymore. I have loops running that prompt Claude and figuring out what to do. My job is to write loops.',
    who: 'Boris Cherny, creator of Claude Code',
    where: 'Meta @Scale, as reported by TechCrunch',
    date: 'June 2026',
    url: 'https://techcrunch.com/2026/06/22/the-ai-world-is-getting-loopy/',
    took: 'The whole folder. A loop is written once and renews itself; you read four lines, not a transcript.',
    home: true,
  },
  {
    id: 'cherny-arc',
    part: 'loops',
    text: 'Two years ago, we wrote source code by hand. We started to transition so agents write the code. And now we’re transitioning to the point where agents are prompting agents that then write the code. As big as the step from source code to agents was, loops are just as important and as big a step.',
    who: 'Boris Cherny',
    where: 'Meta @Scale, as reported by TechCrunch',
    date: 'June 2026',
    url: 'https://techcrunch.com/2026/06/22/the-ai-world-is-getting-loopy/',
    took: 'Why the site is named after the loop and not the agent.',
  },
  {
    id: 'bea-loop',
    part: 'loops',
    text: 'They are typically just LLMs using tools based on environmental feedback in a loop.',
    who: 'Anthropic',
    where: 'Building effective agents',
    date: 'December 2024',
    url: 'https://www.anthropic.com/engineering/building-effective-agents',
    took: 'One bounded pass of claude -p is the whole run. No framework in between.',
  },
  {
    id: 'bea-stop',
    part: 'loops',
    text: 'The task often terminates upon completion, but it’s also common to include stopping conditions (such as a maximum number of iterations) to maintain control.',
    who: 'Anthropic',
    where: 'Building effective agents',
    date: 'December 2024',
    url: 'https://www.anthropic.com/engineering/building-effective-agents',
    took: 'Budget per run, budget per loop, a review date, and two no-progress runs park it. Nothing runs forever.',
    home: true,
  },
  {
    id: 'bea-simple',
    part: 'loops',
    text: 'the most successful implementations weren’t using complex frameworks or specialized libraries. Instead, they were building with simple, composable patterns.',
    who: 'Anthropic',
    where: 'Building effective agents',
    date: 'December 2024',
    url: 'https://www.anthropic.com/engineering/building-effective-agents',
    took: 'Markdown files, a shell script, a permissions fence, launchd. Copy the folder.',
  },
  {
    id: 'sdk-loop',
    part: 'loops',
    text: 'In Claude Code, Claude often operates in a specific feedback loop: gather context -> take action -> verify work -> repeat.',
    who: 'Anthropic',
    where: 'Building agents with the Claude Agent SDK',
    date: 'September 2025',
    url: 'https://claude.com/blog/building-agents-with-the-claude-agent-sdk',
    took: 'Every loop’s definition of done says verify before you report. The morning judge checks that it did.',
  },
  {
    id: 'harness-memory',
    part: 'loops',
    text: 'Each new session begins with no memory of what came before.',
    who: 'Anthropic',
    where: 'Effective harnesses for long-running agents',
    date: 'November 2025',
    url: 'https://www.anthropic.com/engineering/effective-harnesses-for-long-running-agents',
    took: 'Each run re-verifies the last run’s key claim before extending it, and ends with a next: line for the one after.',
  },
  {
    id: 'harness-bridge',
    part: 'loops',
    text: 'Agents need a way to bridge the gap between coding sessions.',
    who: 'Anthropic',
    where: 'Effective harnesses for long-running agents',
    date: 'November 2025',
    url: 'https://www.anthropic.com/engineering/effective-harnesses-for-long-running-agents',
    took: 'A loop’s state file is append-only and dated. That file is the bridge.',
  },
  {
    id: 'goal-docs',
    part: 'loops',
    text: 'You can also schedule work that runs independent of any open session, such as nightly tests or morning triage.',
    who: 'Anthropic',
    where: 'Claude Code docs, Keep Claude working toward a goal',
    date: '2026',
    url: 'https://code.claude.com/docs/en/goal',
    took: 'Nightly is the default cadence. The laptop is the scheduler.',
  },
  {
    id: 'ctx-notes',
    part: 'graphs',
    text: 'Structured note-taking, or agentic memory, is a technique where the agent regularly writes notes persisted to memory outside of the context window.',
    who: 'Anthropic',
    where: 'Effective context engineering for AI agents',
    date: 'September 2025',
    url: 'https://www.anthropic.com/engineering/effective-context-engineering-for-ai-agents',
    took: 'Four lines per loop per night, in files the run cannot edit later. Those notes are what the graph reads.',
    home: true,
  },
  {
    id: 'ctx-finite',
    part: 'graphs',
    text: 'Context, therefore, must be treated as a finite resource with diminishing marginal returns.',
    who: 'Anthropic',
    where: 'Effective context engineering for AI agents',
    date: 'September 2025',
    url: 'https://www.anthropic.com/engineering/effective-context-engineering-for-ai-agents',
    took: 'A run starts from the loop’s state file and the charter, not from last night’s transcript.',
  },
  {
    id: 'research-memory',
    part: 'graphs',
    text: 'The LeadResearcher begins by thinking through the approach and saving its plan to Memory to persist the context, since if the context window exceeds 200,000 tokens it will be truncated and it is important to retain the plan.',
    who: 'Anthropic',
    where: 'How we built our multi-agent research system',
    date: 'June 2025',
    url: 'https://www.anthropic.com/engineering/multi-agent-research-system',
    took: 'The plan lives in the loop, not in the session. The session can die; the plan cannot.',
  },
  {
    id: 'research-state',
    part: 'graphs',
    text: 'In agentic systems, minor changes cascade into large behavioral changes, which makes it remarkably difficult to write code for complex agents that must maintain state in a long-running process.',
    who: 'Anthropic',
    where: 'How we built our multi-agent research system',
    date: 'June 2025',
    url: 'https://www.anthropic.com/engineering/multi-agent-research-system',
    took: 'State is owned by the runner and written to disk between runs. The agent never holds it.',
  },
  {
    id: 'kg-chain',
    part: 'graphs',
    text: 'No single document contains the answer. RAG retrieval won’t chain the facts for you.',
    who: 'Anthropic',
    where: 'Claude Cookbook, Knowledge graph construction',
    date: 'March 2026',
    url: 'https://platform.claude.com/cookbook/capabilities-knowledge-graph-guide',
    took: 'A month of reports is a pile of documents. The graph is how last month’s mistake becomes one query.',
  },
  {
    id: 'memory-docs',
    part: 'graphs',
    text: 'Auto memory lets Claude accumulate knowledge across sessions without you writing anything.',
    who: 'Anthropic',
    where: 'Claude Code docs, How Claude remembers your project',
    date: '2026',
    url: 'https://code.claude.com/docs/en/memory',
    took: 'Their memory remembers your preferences. Ours has to remember your decisions. Same idea, one level up.',
  },
];
